// This file is auto-generated by FlutterFire CLI.
// Run: flutterfire configure
// to regenerate this file for your Firebase project.
//
// PLACEHOLDER — Replace this entire file by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
// in this project directory.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE ALL VALUES BELOW with those from your Firebase project ──
  // Firebase Console → Project Settings → Your Apps → Config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8NHppSU9rDp4u_lVJYa_h_HFYRFvjzMc',
    appId: '1:54445333349:web:cee8f43d8849910a505f8c',
    messagingSenderId: '54445333349',
    projectId: 'diagnosis-center-831ad',
    authDomain: 'diagnosis-center-831ad.firebaseapp.com',
    storageBucket: 'diagnosis-center-831ad.firebasestorage.app',
    measurementId: 'G-748DH5MNKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8NHppSU9rDp4u_lVJYa_h_HFYRFvjzMc',
    appId: '1:54445333349:web:cee8f43d8849910a505f8c',
    messagingSenderId: '54445333349',
    projectId: 'diagnosis-center-831ad',
    storageBucket: 'diagnosis-center-831ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8NHppSU9rDp4u_lVJYa_h_HFYRFvjzMc',
    appId: '1:54445333349:web:cee8f43d8849910a505f8c',
    messagingSenderId: '54445333349',
    projectId: 'diagnosis-center-831ad',
    storageBucket: 'diagnosis-center-831ad.firebasestorage.app',
    iosBundleId: 'com.diagnosiscentre.diagnosisSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8NHppSU9rDp4u_lVJYa_h_HFYRFvjzMc',
    appId: '1:54445333349:web:cee8f43d8849910a505f8c',
    messagingSenderId: '54445333349',
    projectId: 'diagnosis-center-831ad',
    storageBucket: 'diagnosis-center-831ad.firebasestorage.app',
    iosBundleId: 'com.diagnosiscentre.diagnosisSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8NHppSU9rDp4u_lVJYa_h_HFYRFvjzMc',
    appId: '1:54445333349:web:cee8f43d8849910a505f8c',
    messagingSenderId: '54445333349',
    projectId: 'diagnosis-center-831ad',
    authDomain: 'diagnosis-center-831ad.firebaseapp.com',
    storageBucket: 'diagnosis-center-831ad.firebasestorage.app',
    measurementId: 'G-748DH5MNKF',
  );
}
